
macro(check_linux_package package_name)

    execute_process(
        COMMAND  apt list --installed build-essential ${package_name}
        COMMAND  grep -iw ${package_name}
        RESULT_VARIABLE retCode
    )

    if(NOT retCode STREQUAL 0)
       
        message(SEND_ERROR "Package ${package_name} not found.")

    endif()

endmacro()

if(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux)

   message(STATUS "Verifying packages installed on Linux ...")

   check_linux_package("zip")
   check_linux_package("unzip")
   check_linux_package("build-essential")
   check_linux_package("libstdc++-10-dev")
   check_linux_package("gdbserver")
   check_linux_package("openssh-server")
   check_linux_package("libgl1-mesa-dev")
   check_linux_package("libdouble-conversion-dev")
   check_linux_package("libpcre2-16-0")
   check_linux_package("zlib1g")
   check_linux_package("zlib1g-dev")
   check_linux_package("libpcre2-dev")
   check_linux_package("libglib2.0-dev")
   check_linux_package("libgl1-mesa-dev")
   check_linux_package("libglfw3-dev")
   check_linux_package("libgles2-mesa-dev")
   check_linux_package("libegl1-mesa-dev")
   check_linux_package("libegl-dev")
   check_linux_package("libgegl-dev")
   check_linux_package("libatspi2.0-0")
   check_linux_package("libatspi2.0-dev")
   check_linux_package("libudev-dev")
   check_linux_package("libpng-dev")
   check_linux_package("libharfbuzz-dev")
   check_linux_package("libfreetype-dev")
   check_linux_package("libfontconfig1-dev")
   check_linux_package("libmtdev-dev")
   check_linux_package("libinput-dev")
   check_linux_package("libxcb-xkb-dev")
   check_linux_package("libxkbcommon-dev")
   check_linux_package("libx11-xcb-dev")
   check_linux_package("libxcb-composite0-dev")
   check_linux_package("libkf5pulseaudioqt-dev")
   check_linux_package("libfontconfig1-dev")
   check_linux_package("libfreetype6-dev")
   check_linux_package("libx11-dev")
   check_linux_package("libx11-xcb-dev")
   check_linux_package("libxext-dev")
   check_linux_package("libxfixes-dev")
   check_linux_package("libxi-dev")
   check_linux_package("libxrender-dev")
   check_linux_package("libxcb1-dev")
   check_linux_package("libxcb-glx0-dev")
   check_linux_package("libxcb-keysyms1-dev")
   check_linux_package("libxcb-image0-dev")
   check_linux_package("libxcb-shm0-dev")
   check_linux_package("libxcb-icccm4-dev")
   check_linux_package("libxcb-sync-dev")
   check_linux_package("libxcb-xfixes0-dev")
   check_linux_package("libxcb-shape0-dev")
   check_linux_package("libxcb-randr0-dev")
   check_linux_package("libxcb-render-util0-dev")
   check_linux_package("libxcb-util-dev")
   check_linux_package("libxcb-xinerama0-dev")
   check_linux_package("libxcb-xkb-dev")
   check_linux_package("libxkbcommon-dev")
   check_linux_package("libxkbcommon-x11-dev")
   check_linux_package("libxcb-xinput-dev")
   check_linux_package("libxcb-xinput0")
   check_linux_package("libtiff-dev")
   check_linux_package("libgbm-dev")
   check_linux_package("pulseaudio")
   check_linux_package("libdrm-de")
   check_linux_package("libssl-dev")
   check_linux_package("qemu-kvm")
   check_linux_package("qemu-utils")

endif()